[tool.pip-tools]
no-emit-index-url = true

[tool.ruff.lint]
select = [ "E4", "E7", "E9", "F", "UP", "I", "F401" ]

[tool.ruff.lint.isort]
length-sort = true
force-sort-within-sections = true

[tool.ruff.lint.mccabe]
max-complexity = 5
