"""Initial version

Revision ID: d74a6765b50b
Revises: 
Create Date: 2025-01-26 18:03:15.940354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd74a6765b50b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transactions',
    sa.Column('transaction_id', sa.CHAR(length=20), nullable=False),
    sa.Column('user_id', sa.CHAR(length=15), nullable=False),
    sa.Column('value', sa.NUMERIC(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=250), nullable=True),
    sa.Column('balance', sa.NUMERIC(), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_Transactions_user_id'), 'Transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Transactions_user_id'), table_name='Transactions')
    op.drop_table('Transactions')
    # ### end Alembic commands ###
